create database `riped-config`;

DROP TABLE `PROPERTIES`;
CREATE TABLE `PROPERTIES` (
  `ID` INT(11) NOT NULL,
  `APPLICATION` VARCHAR(50) DEFAULT NULL,
  `PROFILE` VARCHAR(50) DEFAULT NULL,
  `LABEL` VARCHAR(50) DEFAULT NULL,
  `KEY` VARCHAR(50) DEFAULT NULL,
  `VALUE` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO PROPERTIES(ID, APPLICATION, PROFILE, LABEL, `KEY`, `VALUE`)
VALUES (1, 'esp-gateway', 'dev', 'master', 'foo', 'The king of fight');

INSERT INTO PROPERTIES(ID, APPLICATION, PROFILE, LABEL, `KEY`, `VALUE`)
VALUES (2, 'esp-gateway', 'test', 'master', 'foo', 'The king of fight');

